.vscode/launch.json
fetch_scripts/generate_testrun_results.py
fetch_scripts/generate_testrun_results.yaml

Now fetch_scripts/generate_testrun_results.py is ready for Jupyter use.

Add scripts to generate testrun results.

---

.vscode/launch.json
fetch_scripts/generate_2way_benchmark.py
fetch_scripts/generate_2way_benchmark.yaml
fetch_scripts/generate_2way_metadata.py
fetch_scripts/generate_testrun_results.yaml

Finish the draft version of data fetching scripts.

Finish the draft version of data fetching scripts.

---

flask/app/models.py
flask/app/templates/widgets/my_list.html
flask/app/templates/widgets/my_show.html
flask/app/views.py

flask: add testruns table and sync table header

---

jupyter/report_portal.ipynb
jupyter/run.sh
jupyter/templates/esxi_fio.md
jupyter/templates/summary_introduction.html

Initiate jupyter files

---

fetch_scripts/flask_load_db.py
flask/app/forms.py
flask/app/models.py
flask/app/templates/widgets/yaml_show.html
flask/app/views.py

flask: add flask_load_db.py and compare report support

---

jupyter/report_portal.ipynb
jupyter/run.sh

Run fetch scripts parallelly and some small fixes

---

jupyter/run.sh

Exclude input in jupyter run.sh

---

jupyter/README.md
jupyter/container/Dockerfile

Add jupyter dockerfile

---

jupyter/README.md

Format Jupyter readme

---

fetch_scripts/flask_load_db.py
flask/app/models.py
flask/app/views.py

modify rw,bs from integer to string

---

jupyter/report_portal.ipynb

Fix issue in report_portal.ipynb and rename title

---

jupyter/container/requirements.txt

Change jupyter requirement nbconvert version to 6.0.7

---

flask/app/models.py

flask: get apache_server from .perf-insight.yaml specified

---

flask/app/forms.py
flask/app/views.py

flask: add call jupiter to generate compare report

---

flask/app/views.py

flask: correct targe name when copy from testrun

---

flask/app/views.py

flask: update benchmark report dir to 2way_comparison_xxxxxx

---

flask/app/views.py

flask: save report to reports instead of benchmark_reports

---

jupyter/report_portal.ipynb

Change MI/MR color; Read flask address from .perf-insight.yaml

---

flask/app/views.py

flask: mount perf-insight.yaml when call jupiter

---

flask/app/models.py

flask: correct test result rawdata url

---

flask/app/__init__.py
flask/app/templates/widgets/yaml_show.html

flask: add progress bar while waiting generate jupiter report

---

flask/app/views.py

flask: read yaml from /opt/perf-insight/data_process in YamlFormView

---

jupyter/report_portal.ipynb

Read metadata csv directly

---

jupyter/README.md

Correct jupyter README

---

flask/app/views.py

flask: get data from form instead of request when post

---

flask/app/forms.py
flask/app/templates/widgets/testrun_new.html
flask/app/views.py

flask: add NewTestrunFormView to allow user upload data from web

---

flask/app/models.py
flask/app/views.py

flask: add ComparedResult to save compared history

---

jupyter/README.md
jupyter/container/Dockerfile
jupyter/run.sh

Add shotcut icon in jupyter report

---

jupyter/report_portal.ipynb

Add Summary section(TODO:run generate_summary script)

---

flask/app/models.py
flask/app/views.py

flask: add net test run and result views

---

data_process/flask_load_db.py

Added below 2 options to specify network or storage test result
-network              write net test result
-storage              write storage test result

flask: update flask_load_db.py to support network result loading

---

data_process/flask_load_db.py
data_process/gather_testrun_datastore.py
data_process/process_testrun.sh
flask/app/views.py
jupyter/templates/introduction_esxi_uperf.md

Support loading data from Flask.
Support generating benchmark report from Flask.

Update the scripts to make it work for the Flask.

---

flask/app/views.py

flask: add compare action to network test runs

---

flask/app/views.py

flask: add menu NetworkPerformance and StoragePerformance

---

jupyter/templates/introduction_azure_fio.md
jupyter/templates/introduction_azure_uperf.md

Add azure_fio and azure_uperf introductions

---

cli_tool/README.md

Add help messages for the `testrun-imports` command.

Add help messages for the `testrun-imports` command to README.md
